title: 阿翰小筆記
theme: paper-mod

copyright: Rhan0
defaultContentLanguage: zh-tw
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
timeZone: Asia/Taipei
markup:
  goldmark:
    renderer:
      unsafe: true

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    author: Rhan0
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "人生 Debug 中。這裡寫些開發心得、生活感想，還有生活裡不務正業的瞬間。"
    mainSections: ["post"]
    defaultTheme: auto
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowShareButtons: true
    homeInfoParams:
        Title: "console.log(人生)"
        Content: >
            人生 Debug 中。這裡寫些開發心得、生活感想，還有生活裡不務正業的瞬間。（功能尚未全數實作完畢）。

    assets:
        disableHLJS: true