baseURL: "/"
title: 阿翰前端小筆
theme: paper-mod

copyright: Rhan0
defaultContentLanguage: zh-tw
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "My description"
    author: Rhan0
    mainSections: ["post"]
    defaultTheme: auto
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    homeInfoParams:
        Title: "你好 \U0001F44B 歡迎來到阿翰的筆記"
        Content: >
            寫下開發過程的筆記，幫助自己在學習的路上留下痕跡

    socialIcons:
        - name: github
          url: "https://github.com/rhanlin"

    assets:
        disableHLJS: true